feat: Updating dependencies for Capacitor 5
ionic-team/create-capacitor-plugin pull request #85
Opened 2023-03-23 21:31 UTC by theproducer

2023-03-24 00:59 UTC, markemer commented on assets/plugin-template/android/build.gradle
> +        classpath 'com.android.tools.build:gradle:7.2.2'
Is this the gradle version we want to pin? Or should it be one of the 7.4.1 ones?

2023-03-24 14:11 UTC, jcesarmobile requested changes
Added a few comments
Also gradle wrapper should be updated to 7.5 (the properties file and the actual wrapper files)
Also the plugin should switch to using namespace instead of package (like https://github.com/ionic-team/capacitor-plugins/pull/1503, might require code changes on the script that creates the plugin as it's probably writing the package name in the AndroidManifest.xml and should be switched to using a namespace)

2023-03-24 20:09 UTC, markemer commented on src/template.ts
> +export const CAPACITOR_VERSION = '^5.0.0-alpha.1';
Yeah, and in either case, we'll have to pin this again on release.

2023-03-27 15:14 UTC, jcesarmobile requested changes
Missed this previous comment:
> Also gradle wrapper should be updated to 7.5 (the properties file and the actual wrapper files)

2023-03-27 15:46 UTC, giralte-ionic approved these changes

2023-03-28 15:14 UTC, IT-MikeS approved these changes

2023-03-28 17:38 UTC, giralte-ionic approved these changes

2023-03-30 08:46 UTC, jcesarmobile requested changes
enableJetifier should be removed from gradle.properties
https://github.com/ionic-team/create-capacitor-plugin/blob/main/assets/plugin-template/android/gradle.properties#L24

2023-03-30 13:33 UTC, IT-MikeS approved these changes

2023-03-30 14:16 UTC, jcesarmobile approved these changes

2023-03-30 14:36 UTC, merged